using BaseLib.Utils;
using HermitMod.Extensions;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Helpers;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.CardPools;
using MegaCrit.Sts2.Core.Nodes.Rooms;
using MegaCrit.Sts2.Core.Nodes.Vfx;
using MegaCrit.Sts2.Core.ValueProps;

namespace HermitMod.Cards;

/// <summary>
/// Unplayable. If this is Dead On at the end of your turn, deal 13 damage to EVERYONE.
/// Generated by Midnight card. Not in card pool.
/// </summary>
[Pool(typeof(CurseCardPool))]
public sealed class ImpendingDoom : HermitCard
{
    public override int MaxUpgradeLevel => 0;
    public override bool HasDeadOn => true;

    protected override bool ShouldGlowGoldInternal => false;
    protected override bool ShouldGlowRedInternal => IsDeadOn;
    public override bool HasTurnEndInHandEffect => IsDeadOn;

    private const int DamageAmount = 13;

    public ImpendingDoom() : base(-2, CardType.Curse, CardRarity.Curse, TargetType.None) { }

    public override IEnumerable<CardKeyword> CanonicalKeywords => [CardKeyword.Unplayable];

    protected override IEnumerable<DynamicVar> CanonicalVars => [new DamageVar(DamageAmount, ValueProp.Unpowered)];

    public override string CustomPortraitPath => "impending_doom.png".BigCardImagePath();
    public override string PortraitPath => "impending_doom.png".CardImagePath();
    public override string BetaPortraitPath => "beta/impending_doom.png".CardImagePath();

    public override async Task OnTurnEndInHand(PlayerChoiceContext ctx)
    {
        ForceSetDeadOnForPlay(true);
        Creature[] targets = [Owner.Creature, ..CombatState!.HittableEnemies];
        foreach (Creature target in targets)
        {
            NFireBurstVfx child = NFireBurstVfx.Create(target, 0.75f)!;
            NCombatRoom.Instance?.CombatVfxContainer.AddChildSafely(child);
        }

        await DamageCmd.Attack(DynamicVars.Damage.BaseValue).FromCard(this).Targeting(Owner.Creature).Execute(ctx);
        await DamageCmd.Attack(DynamicVars.Damage.BaseValue).FromCard(this).TargetingAllOpponents(CombatState!).Execute(ctx);
        
        await MaintanceDeadOnAfterPlayed(ctx, null);
        ClearDeadOnForPlay();
    }
}
